### ISSUE TITLE
Status topics not being sent to MQTT

### ISSUE THREAD

**Issue by sparkydave1981** [maragelis/ParadoxMqtt32#24]
When viewing the MQTT topics in MQTTlens I am only getting data on `paradox32CTL/out` but no data on the zone topics such as `paradox32CTL/hassio/0/zone1`.  Also, even the 'out' topic does not seem to be showing all event.  Any tips?

**Comment by sparkydave1981** [comment]
I have the below sensors in Home Assistant but only the one for Area0 is working.  I can arm / disarm the Paradox system via MQTT using this new interface, but only Area0 gives a status back, nothing from Area1.

```
sensor:
  - platform: mqtt
    name: paradox_alarm_status_area1
    state_topic: 'paradox32CTL/hassio/Arm/0'
    force_update: true
  - platform: mqtt
    name: paradox_alarm_status_area2
    state_topic: 'paradox32CTL/hassio/Arm/1'
    force_update: true
```

Area1 shows as 'unknown'.
